import heroMk from '../images/mk-case-study/hero-image.png'
import mkImg1 from '../images/mk-case-study/image-1.png'
import mkImg2 from '../images/mk-case-study/image-2.png'
import mkImg3 from '../images/mk-case-study/image-3.png'
import mkImg4 from '../images/mk-case-study/image-4.png'

import heroWL from '../images/wl-case-study/hero-img.png'
import wlImg1 from '../images/wl-case-study/img1.png'
import wlImg2 from '../images/wl-case-study/img2.png'
import wlImg3 from '../images/wl-case-study/img3.png'
import wlImg4 from '../images/wl-case-study/img4.png'

import type { ImageMetadata } from 'astro'

export interface Project {
  title: string
  description: string
  tags: string[]
  imageUrl: ImageMetadata
  imageAlt: string
  slug: string
  caseStudy?: CaseStudyContent
}

export interface CaseStudyContent {
  subtitle: string
  projectUrl: string
  heroImage: ImageMetadata
  heroImageAlt: string
  industry: string
  category: string[]
  techStack: string[]
  liveLink: string
  introduction: {
    label: string
    heading: string
    body: string
  }
  design: {
    description: string
    images: Array<{ src: ImageMetadata; alt: string }>
  }
  development: {
    body: string
  }
  conclusion: {
    quote: string
    body: string
  }
}

function cs(
  overrides: Partial<CaseStudyContent> & {
    title: string
    subtitle: string
    projectUrl: string
    heroImage: ImageMetadata
    heroImageAlt: string
    industry: string
    category: string[]
    techStack: string[]
    liveLink: string
    introHeading: string
    introBody: string
    designDescription: string
    designImages: Array<{ src: ImageMetadata; alt: string }>
    devBody: string
    conclusionQuote: string
    conclusionBody: string
  },
): CaseStudyContent {
  return {
    subtitle: overrides.subtitle,
    projectUrl: overrides.projectUrl,
    heroImage: overrides.heroImage,
    heroImageAlt: overrides.heroImageAlt,
    industry: overrides.industry,
    category: overrides.category,
    techStack: overrides.techStack,
    liveLink: overrides.liveLink,
    introduction: {
      label: overrides.introduction?.label ?? 'Introduction',
      heading: overrides.introHeading,
      body: overrides.introBody,
    },
    design: {
      description: overrides.designDescription,
      images: overrides.designImages,
    },
    development: {
      body: overrides.devBody,
    },
    conclusion: {
      quote: overrides.conclusionQuote,
      body: overrides.conclusionBody,
    },
  }
}

export const projects: Project[] = [
  {
    title: 'Merge Konflict',
    description:
      'A full-featured booking and scheduling platform for a modern barbershop.',
    tags: ['Next.js', 'Sanity CMS'],
    imageUrl: heroMk,
    imageAlt: 'DJ Merge Konflict Website Project',
    slug: '/case-study/mergekonflict',
    caseStudy: {
      subtitle:
        'is a personal brand website for a electronic music DJ, featuring an upcoming shows calendar, a custom SoundCloud audio player, and a spam-free contact form.',
      projectUrl: 'https://mergekonflict.com',
      heroImage: heroMk,
      heroImageAlt: 'DJ Website hero mockup',
      industry: 'Music & Entertainment',
      category: ['UX/UI Design', 'Web Development', 'CMS Integration'],
      techStack: [
        'Next.js',
        'Sanity CMS',
        'Tailwind CSS',
        'Shadcn',
        'Soundcloud API',
      ],
      liveLink: 'https://mergekonflict.com',
      introduction: {
        label: 'Introduction',
        heading: 'The making of the new Merge Konflict website',
        body: 'For a working DJ, a website is the difference between being discoverable and being invisible. Merge Konflict had the music, the shows, and the fanbase — but no digital stage. This project was built using Spec-Driven Agentic Engineering, a methodology where the developer orchestrates a team of specialized AI agents through structured specification documents. Every line of production code was generated by AI, guided by specs, and reviewed before merge. The result: a live, polished site with perfect Lighthouse scores, deployed in under two weeks of part-time work.',
      },
      design: {
        description:
          "The design language draws from the raw energy of underground rave culture — dark, gritty, and uncompromising. A custom shadcn theme preset anchors the visual identity with deep mahogany backgrounds, a striking red accent for CTAs and links, and soft off-white surfaces for light mode. The artist name sits vertically on the hero's left edge, rotated -90 degrees — an unconventional layout that mirrors the genre's break from tradition. Every section below the hero gets generous whitespace, letting the content breathe on both mobile and desktop. A light/dark toggle gives fans control over their viewing experience.",
        images: [
          {
            src: mkImg1,
            alt: 'Barbershop booking interface',
          },
          {
            src: mkImg2,
            alt: 'Barbershop admin dashboard',
          },
          {
            src: mkImg3,
            alt: 'Barbershop mobile booking view',
          },
          {
            src: mkImg4,
            alt: 'Barbershop service details',
          },
        ],
      },
      development: {
        body: "The site was built on Next.js 16 with React Server Components handling all data-fetching sections, reserving Client Components only where browser interactivity is required — the SoundCloud player, contact form, and theme toggle. Sanity CMS powers every piece of content through an embedded Studio at /studio, with three document types covering shows, site settings, and contact submissions; a webhook triggers on-demand ISR so published changes appear on the live site within seconds. The most stubborn challenge came from SoundCloud's 2025 API migration: the embedded player no longer accepted the new URN-based playlist identifiers, requiring a workaround that extracts the legacy numeric ID, stores it as a CMS field, and constructs the embed URL dynamically. A similar debugging effort resolved a production crash caused by a null image reference after adding a new schema field, and a field-name mismatch between the contact form's Server Action and client component was aligned to restore end-to-end submission flow.",
      },
      conclusion: {
        quote: '"A Website as Good as the Music"',
        body: 'The site launched with nearly perfect Lighthouse scores across all four categories — Performance, Accessibility, Best Practices, and SEO. The contact form is spam-free thanks to a multi-layered invisible defense (honeypots, timing analysis, and Upstash rate limiting). Merge Konflict now updates his own schedule, bio, and playlist through a simple Studio interface. The Spec-Driven Agentic Engineering methodology proved itself: a solo developer, zero lines of implementation code, and a team of specialized AI agents that handled everything from design extraction to production deployment.',
      },
    },
  },
  {
    title: 'Walnut Lawn',
    description:
      'A fast, CMS-driven lawn care website that converts neighbors into customers.',
    tags: ['Astro', 'Sanity CMS'],
    imageUrl: heroWL,
    imageAlt: 'Walnut Lawn Website Project',
    slug: '/case-study/walnut-lawn',
    caseStudy: {
      subtitle:
        'is a custom-built, high-performance website for a faith-based, family-owned lawn care business.',
      projectUrl: 'https://walnutlawn.net',
      heroImage: heroWL,
      heroImageAlt: 'Walnut Lawn hero mockup',
      industry: 'Home Services / Landscaping',
      category: ['Web Design', 'Web Development', 'CMS Integration'],
      techStack: ['Astro', 'Sanity CMS', 'Tailwind CSS', 'Netlify'],
      liveLink: 'https://walnutlawn.net',
      introduction: {
        label: 'Introduction',
        heading: 'The making of the new Walnut Lawn website',
        body: 'For a family-owned lawn care business, word-of-mouth and social media can only take you so far. Walnut Lawn had built a stellar reputation in their Walnut Creek neighborhood through reliable service and personal care, but they lacked a professional digital storefront to capture leads and showcase their work. Grant Jackson and his team needed more than just a pretty page — they needed a lead-generation machine that reflected their "Faith, Family, & Beautiful Lawns" motto. The project was built to give customers a seamless way to request quotes, land more jobs, and establish online credibility. Most importantly, Grant needed full autonomy to update services and testimonials himself without calling a developer every time. The result is a modern, fast, and easily-managed website that works as hard as the team does.',
      },
      design: {
        description:
          'The design language draws from the lush, natural beauty of a well-maintained outdoor space — earthy greens, warm neutrals, and clean, organic layouts. I built the entire visual identity from scratch around Grant\'s faith and family values, ensuring every element felt approachable yet highly professional. A minimalist approach contrasts with the inherently "messy" work of lawn care, giving the high-quality project photography room to breathe. Generous whitespace and clear typography guide potential customers effortlessly from the hero section down to the "Get Free Estimate" call-to-action. The mobile experience was prioritized from day one, since most homeowners search for lawn services on their phones while out and about.',
        images: [
          {
            src: wlImg1,
            alt: 'Walnut Lawn hero section with call-to-action',
          },
          {
            src: wlImg2,
            alt: 'Walnut Lawn services grid and feature cards',
          },
          {
            src: wlImg3,
            alt: 'Walnut Lawn mobile contact form view',
          },
          {
            src: wlImg4,
            alt: 'Walnut Lawn testimonial and project gallery section',
          },
        ],
      },
      development: {
        body: "The site was built on Astro paired with Tailwind CSS to ensure near-instant page loads, with critical CSS inlined and zero client-side JavaScript shipped by default. Sanity CMS powers every piece of content through an embedded Studio, with three document types covering services, testimonials, and site settings; a webhook triggers on-demand rebuilds on Netlify so published changes appear on the live site within seconds. Netlify Forms handles all \"Get Free Estimate\" submissions, forwarding them directly to the team's work email without requiring a separate backend. The most stubborn challenge came from integrating Sanity CMS and configuring the build hooks to ensure seamless live updates in production — achieving zero-disruption deployments while avoiding stale data required meticulous configuration of Sanity's webhooks with Netlify's build triggers. A similar debugging effort resolved a production crash caused by a missing image reference in a new schema field, which was patched by adding proper fallback handling in the Astro components.",
      },
      conclusion: {
        quote: '"A Website as Good as the Lawn Care"',
        body: 'The site launched with near-perfect Lighthouse scores across Performance, Accessibility, Best Practices, and SEO — a major improvement from the initial poor metrics. Grant now has a professional digital asset that actively works for his business 24/7, generating leads and instilling confidence in potential customers before they ever pick up the phone. He loves that he can make updates to the site himself anytime he wants and has been getting significantly more business inquiries since the site went live. The project successfully transformed a social-media-only operation into a polished, lead-generating machine that truly represents the quality of their work.',
      },
    },
  },
]
